dex:
  connectors:
    github:
      config:
        clientID: vault:gitOps/daveconde/environment-dconde-cjxd4-dev/dex-connectors-github-config:clientID
        clientSecret: vault:gitOps/daveconde/environment-dconde-cjxd4-dev/dex-connectors-github-config:clientSecret
        name: GitHub
        type: github
  domain: jenkins-x.rocks
enabledConnector: GitHub
